### PR TITLE
Add functional smoke tests and automated testing workflow

### LINKED ISSUE #171: Add basic functional "smoke test"
# 💡 Summary #
Add a functional, end-to-end test that performs very basic validation of ScubaGoggles functionality.

## Motivation and context ##
Currently all functional testing needs to be done manually, leading to delayed discovery of potential issues. Due to GWS's limited API, we can't implement full functional testing, but we could implement a basic "smoke test" which would allow us to quickly identify some issues.

## Implementation notes ##
Dependent on:
- https://github.com/cisagov/ScubaGoggles/pull/165
- https://github.com/cisagov/ScubaGoggles/pull/163

After those two PRs are merged, we can add a GitHub trigger that runs ScubaGoggles and performs basic validation of the report, such as:
- The provider output is valid json
- There is no missing output
- No API calls or functions produced exceptions

I recommend referring to the ScubaGear smoke test as a starting point for implementing this functionality.

See:
- https://github.com/cisagov/ScubaGear/blob/main/.github/workflows/run_smoke_test.yaml
- https://github.com/cisagov/ScubaGear/tree/main/Testing/Functional/SmokeTest

## Acceptance criteria ##
- [ ] A basic smoke test has been implemented
- [ ] The smoke test has been added to the GitHub workflow

### PR DESCRIPTION
**Pull request by mitchelbaker-cisa**
## 🗣 Description ##

Added smoke tests ([/Testing/Functional/SmokeTests/smoke_test.py](https://github.com/cisagov/ScubaGoggles/blob/171-functional-smoke-test/Testing/Functional/SmokeTests/smoke_test.py)) to verify the following: 
- scubagoggles output (all files/directories are created)
- ScubaResults.json (determine if there are API exceptions or other errors produced) 
- Parent/Individual html reports (navigation links, agency data, baseline report data, and policy tables display as expected)

Added an automated testing workflow ([.github/workflows/run_smoke_test.py](https://github.com/cisagov/ScubaGoggles/blob/171-functional-smoke-test/.github/workflows/run_smoke_test.yml)) that runs the smoke tests against Windows/macOS and across different python versions. The workflow runs when a PR is opened, reopened, synchronized (a new commit is added), and when a commit is pushed into main. 

The workflow has been tested against Python versions ranging from 3.9 - 3.12. Due to limitations with the numpy package testing is limited < v3.9. (numpy v1.24.4 is the highest supported version for Python v3.8.4 so there's issues with downgrading to numpy v1.26.4)

### 💭 Motivation and context

We manually test scubagoggles output, python min/max supported versions, etc. which is resource intensive. The purpose of these smoke tests and automated workflows is to ease the burden of testing when new PRs are opened, changes are added into main, and prior to releases. 

closes #171 

Create future todos: 
- [x] Use Selenium to check for the correct baseline and tool version in the agency table (e.g. 0.2, 0.2.0) - #339 
- [x] Update run_smoke_test.py to take in input when running the workflow manually. This will allow our developers to input specific Python versions as opposed to hardcoded values.  - #340 
- [x] Update docs on how to run smoke tests - #341 

## 🧪 Testing

```
pip install pytest selenium
```

A service account is required to run the smoke tests. Replace "subjectemail@mail.com" with your subject email, then replace "domain@domain.com" with the domain you're running scubagoggles against.
```
pytest -s -vvv ./Testing/Functional/SmokeTests/ --subjectemail="subjectemail@mail.com" --domain="domain.com"
```

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] If applicable, *All* future TODOs are captured in issues, which are referenced in the PR description.
- [x] The relevant issues PR resolves are linked preferably via [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [x] All relevant type-of-change labels have been added.
- [x] I have read and agree to the [CONTRIBUTING.md](https://github.com/cisagov/ScubaGoggles/blob/main/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [ ] All relevant repo and/or project documentation has been updated to reflect the changes in this PR.
- [x] Tests have been added and/or modified to cover the changes in this PR.
- [x] All new and existing tests pass.

## ✅ Pre-merge Checklist

- [ ] This PR has been smoke tested to ensure main is in a functional state when this PR is merged.
- [ ] Squash all commits into one PR level commit using the `Squash and merge` button.

## ✅ Post-merge Checklist

- [ ] Delete the branch to clean up.
- [ ] Close issues resolved by this PR if the [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) did not activate.

### CODE REVIEW

**Review by adhilto — APPROVED** [review]
Huge step in the right direction. And it already found a [bug](https://github.com/cisagov/ScubaGoggles/issues/337). Looks good. I'm going to go ahead and approve but my one ask would be to create an issue (or issues) for the various TODO items you identified.

**Comment by mitchelbaker-cisa** [comment]
> Huge step in the right direction. And it already found a [bug](https://github.com/cisagov/ScubaGoggles/issues/337). Looks good. I'm going to go ahead and approve but my asks would be to create an issue (or issues) for the various TODO items you identified and to make the Pylinter happy.

Thanks! Issues have been created for the various todo items and the Pylint check is passing.

**Review by snarve — COMMENTED** [review]
Great job Mitchel!

When I try to run the tests, I am getting an error:

image


I tried adding the relative path, but it still complains. Did I miss any step?

**Comment by mitchelbaker-cisa** [comment]
> Great job Mitchel!
> 
> When I try to run the tests, I am getting an error:
> 
> image
> 
> image
> 
> I tried adding the relative path, but it still complains. Did I miss any step?

Thanks Sheetal! The import for gws_products() changed because I rebased after Roy's PR was merged into main. Should resolve after running `git pull --rebase origin 171-functional-smoke-test` then rerunning the test suite.

**Comment by snarve** [comment]
> > Great job Mitchel!
> > When I try to run the tests, I am getting an error:
> > image
> > image
> > I tried adding the relative path, but it still complains. Did I miss any step?
> 
> Thanks Sheetal! The import for gws_products() changed because I rebased after Roy's PR was merged into main. Should resolve after running `git pull --rebase origin 171-functional-smoke-test` then rerunning the test suite.

Now its failing on the Chrome driver:

image

**Comment by LaurenBassett** [comment]
Running Through Workflow on Mac. Out of the box, I get this error:
Screenshot 2024-08-21 at 12 15 48 PM

Will troubleshoot and report findings

**Comment by adhilto** [comment]
Let me document this since I didn't earlier. I also ran the smote test manually, and it worked for me. I tested on a Windows.

**Comment by adhilto** [comment]
> Running Through Workflow on Mac. Out of the box, I get this error: 
> 
> Will troubleshoot and report findings

@LaurenBassett That looks like the Pandas/numpy interrogability error we've been struggling with elsewhere

**Comment by LaurenBassett** [comment]
> > Running Through Workflow on Mac. Out of the box, I get this error:
> > Will troubleshoot and report findings
> 
> @LaurenBassett That looks like the Pandas/numpy interrogability error we've been struggling with elsewhere

Yup. Just fixed it and ran again. I figured I'd document every piece of the flow though, just for documentation's sake. I downgraded numpy, I know we had discussed other ways to fix in our sync yesterday though.

**Comment by LaurenBassett** [comment]
Seeing this message now, it may be user error on my part?
 ```

WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11a2822a0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/redacted
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11a283020>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/redacted
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11a283200>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/readacted
============================================================= short test summary info ==============================================================
FAILED Testing/Functional/SmokeTests/smoke_test.py::SmokeTest::test_scubagoggles_output - Failed: An error occurred, Command 'scubagoggles gws --subjectemail redacted@redacted.org --quiet' returned non-zero exit status 127.
FAILED Testing/Functional/SmokeTests/smoke_test.py::SmokeTest::test_scubagoggles_report - Failed: An error occurred, Expected the reports table to have a length of 10
=========================================================== 2 failed, 1 passed in 1.08s ============================================================

```

**Comment by mitchelbaker-cisa** [comment]
> Seeing this message now, it may be user error on my part?
> 
> ```
> 
  > WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11a2822a0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/redacted
> WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11a283020>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/redacted
> WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11a283200>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/readacted
> ============================================================= short test summary info ==============================================================
> FAILED Testing/Functional/SmokeTests/smoke_test.py::SmokeTest::test_scubagoggles_output - Failed: An error occurred, Command 'scubagoggles gws --subjectemail redacted@redacted.org --quiet' returned non-zero exit status 127.
> FAILED Testing/Functional/SmokeTests/smoke_test.py::SmokeTest::test_scubagoggles_report - Failed: An error occurred, Expected the reports table to have a length of 10
> =========================================================== 2 failed, 1 passed in 1.08s ============================================================
> ```

Hmm interesting. I think the urllib3 `Errno 61` error is caused when selenium driver.quit() is called prematurely. That would explain the test_scubagoggles_report error because the report does not contain all baselines. That points to the root cause being in test_scubagoggles_output. Can you successfully create a report when just running `scubagoggles gws --subjectemail redacted@redacted.org --quiet`?

**Comment by adhilto** [comment]
> Seeing this message now, it may be user error on my part?
> 
> ```
> 
> WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11a2822a0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/redacted
> WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11a283020>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/redacted
> WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11a283200>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/readacted
> ============================================================= short test summary info ==============================================================
> FAILED Testing/Functional/SmokeTests/smoke_test.py::SmokeTest::test_scubagoggles_output - Failed: An error occurred, Command 'scubagoggles gws --subjectemail redacted@redacted.org --quiet' returned non-zero exit status 127.
> FAILED Testing/Functional/SmokeTests/smoke_test.py::SmokeTest::test_scubagoggles_report - Failed: An error occurred, Expected the reports table to have a length of 10
> =========================================================== 2 failed, 1 passed in 1.08s ============================================================
> ```

This looks like a network issue to me. Maybe your corporate proxy is blocking the download?

**Comment by mitchelbaker-cisa** [comment]
@LaurenBassett I would also check that the credentials.json is in the correct format from the [Using a Service Account](https://github.com/cisagov/ScubaGoggles/blob/main/docs/authentication/ServiceAccount.md#using-a-service-account) steps.

**Comment by LaurenBassett** [comment]
> @LaurenBassett I would also check that the credentials.json is in the correct format from the [Using a Service Account](https://github.com/cisagov/ScubaGoggles/blob/main/docs/authentication/ServiceAccount.md#using-a-service-account) steps.

Somehow missed the part about the service account. That was a huge blocker for sure. 

Running it again, the ```scubagoggles gws --subjectemail redacted@redacted.org --quiet``` command works just fine. I'm still running into issues with the full command. 

```
"serviceaccount@projectname.iam.gserviceaccount.com"
=============================================================== test session starts ================================================================
platform darwin -- Python 3.12.4, pytest-8.3.2, pluggy-1.5.0 -- .../CISA_SCuBA/.venv/bin/python
cachedir: .pytest_cache
rootdir: ../CISA_SCuBA/ScubaGoggles
configfile: pytest.ini
collected 3 items                                                                                                                                  

Testing/Functional/SmokeTests/smoke_test.py::SmokeTest::test_scubagoggles_output Password:
PASSED
Testing/Functional/SmokeTests/smoke_test.py::SmokeTest::test_scubaresults PASSED
Testing/Functional/SmokeTests/smoke_test.py::SmokeTest::test_scubagoggles_report FAILED

===================================================================== FAILURES =====================================================================
________________________________________________________ SmokeTest.test_scubagoggles_report ________________________________________________________

self = <smoke_test.SmokeTest object at 0x113a85730>, browser = <SmokeTests.selenium_browser.Browser object at 0x113a6cf50>
domain = 'serviceaccount@projectname.iam.gserviceaccount.com'

    def test_scubagoggles_report(self, browser, domain):
        """
        Test if the generated baseline reports are correct,
        i.e. BaselineReports.html, CalendarReport.html, ChatReport.html
        """
        try:
            output_path: str = get_output_path()
            report_path: str = prepend_file_protocol(os.path.join(output_path, BASELINE_REPORTS))
            browser.get(report_path)
>           run_selenium(browser, domain)

Testing/Functional/SmokeTests/smoke_test.py:69: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
Testing/Functional/SmokeTests/smoke_test_utils.py:154: in run_selenium
    verify_tenant_table(browser, domain, True)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

browser = <SmokeTests.selenium_browser.Browser object at 0x113a6cf50>, domain = 'serviceaccountname@projectname.iam.gserviceaccount.com'
parent = True

    def verify_tenant_table(browser, domain, parent):
   ...
        customer_domain = tenant_table_rows[1].find_elements(By.TAG_NAME, "td")[0].text
>       assert customer_domain == domain
E       AssertionError

Testing/Functional/SmokeTests/smoke_test_utils.py:259: AssertionError

During handling of the above exception, another exception occurred:

self = <smoke_test.SmokeTest object at 0x113a85730>, browser = <SmokeTests.selenium_browser.Browser object at 0x113a6cf50>
domain = 'serviceaccoint@projectname.iam.gserviceaccount.com'

    def test_scubagoggles_report(self, browser, domain):
       ...
        except (ValueError, AssertionError, Exception) as e:
            browser.quit()
>           pytest.fail(f"An error occurred, {e}")
E           Failed: An error occurred,

Testing/Functional/SmokeTests/smoke_test.py:72: Failed
-------------------------------------------------------------- Captured log teardown ---------------------------------------------------------------
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x127ecbe60>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/8bbf2c22ca41e8c27b1ab39281b802b5
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113bce750>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/8bbf2c22ca41e8c27b1ab39281b802b5
WARNING  urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x127ecbe00>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/8bbf2c22ca41e8c27b1ab39281b802b5
============================================================= short test summary info ==============================================================
FAILED Testing/Functional/SmokeTests/smoke_test.py::SmokeTest::test_scubagoggles_report - Failed: An error occurred,
=========================================================== 1 failed, 2 passed in 59.22s =========================================
```

**Comment by snarve** [comment]
Update: disconnecting from the vpn help resolve the Chrome driver issue

Regular reports using the service account as the auth method works

Running the smoke tests: my results are similar to what @LaurenBassett posted (the latest screencapture)

**Comment by mitchelbaker-cisa** [comment]
> Somehow missed the part about the service account. That was a huge blocker for sure.
> 
> Running it again, the `scubagoggles gws --subjectemail redacted@redacted.org --quiet` command works just fine. I'm still running into issues with the full command.

No worries, will be sure to reference the service account setup when building out the smoke test documentation. 

When running `pytest -s -vvv ./Testing/Functional/SmokeTests/ --subjectemail="subjectemail@mail.com" --domain="domain@domain.com"` the value passed into the --domain parameter must match the Customer Domain column in the reports. 

Screenshot (180)_LI

**Comment by LaurenBassett** [comment]
> > Somehow missed the part about the service account. That was a huge blocker for sure.
> > Running it again, the `scubagoggles gws --subjectemail redacted@redacted.org --quiet` command works just fine. I'm still running into issues with the full command.
> 
> No worries, will be sure to reference the service account setup when building out the smoke test documentation.
> 
> When running `pytest -s -vvv ./Testing/Functional/SmokeTests/ --subjectemail="subjectemail@mail.com" --domain="domain.com"` the value passed into the --domain parameter must match the Customer Domain column in the reports, otherwise the `assert customer_domain == domain` check fails.
> 
> Screenshot (180)_LI

Screenshot 2024-08-21 at 4 29 16 PM

That did it! I have it running successfully on Mac now. I guess I got a little confused with the service account vs. domain vs. admin account.

**Comment by mitchelbaker-cisa** [comment]
> That did it! I have it running successfully on Mac now. I guess I got a little confused with the service account vs. domain vs. admin account.

Awesome! Thanks for documenting the setup process, a lot of good feedback here. Are there areas which can be more clear, perhaps changing `domain` to `customerdomain`?

**Comment by adhilto** [comment]
> > That did it! I have it running successfully on Mac now. I guess I got a little confused with the service account vs. domain vs. admin account.
> 
> Awesome! Thanks for documenting the setup process, a lot of good feedback here. Are there areas which can be more clear, perhaps changing the `domain` parameter to `customerdomain`?

`customerdomain` would make it consistent with scubagogles parameter `customerid`

**Comment by LaurenBassett** [comment]
> > That did it! I have it running successfully on Mac now. I guess I got a little confused with the service account vs. domain vs. admin account.
> 
> Awesome! Thanks for documenting the setup process, a lot of good feedback here. Are there areas which can be more clear, perhaps changing the `domain` parameter to `customerdomain`?

I think there are a few bits that would be helpful in the documentation: 
- I was unclear what subject email was referring to; my scuba domain email address, or the service account's email address. 
- Having the example be subject@domain.com, or even user@domain.com may be clearer 
- I'd make a stronger note about the need for a service account and to ensure credentials are updated
- The instructions for what to replace are confusing:
>  A service account is required to run the smoke tests. Replace "[subjectemail@mail.com](mailto:subjectemail@mail.com)" with your subject email, then replace "[domain@domain.com](mailto:domain@domain.com)" with the domain you're running scubagoggles against.
- I was using myuser@domain.com for the domain, not the basic domain, which was causing that last error

**Review by LaurenBassett — APPROVED** [review]

**Pull request merged**
