### PR TITLE
Added prerequisite to Common Controls Policy Group 11

### LINKED ISSUE #222: Pre-Requisite needs to be Added to Common Controls Policy Group 11
Based on the the google update below, a prerequisite needs to be added to Common Controls Policy Group 11 stating that the "Allow users to install Chat apps" needs to be set to "On".

[Google Blog Update Post](http://workspaceupdates.googleblog.com/2024/02/updates-to-google-workspace-marketplace.html)

### PR DESCRIPTION
**Pull request by jkaufman-mitre**
## 🗣 Description ##

Added pre-requisite to Common Controls Policy Group 11 stating that the "Allow users to install chat apps" needs to be set to "On"

Fixes #222 

### 💭 Motivation and context

Google Product Update

## ✅ Pre-approval checklist ##

- [ ] This PR has an informative and human-readable title.
- [ ] Changes are limited to a single goal - *eschew scope creep!*
- [ ] If applicable, *All* future TODOs are captured in issues, which are referenced in the PR description.
- [ ] The relevant issues PR resolves are linked preferably via [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [ ] All relevant type-of-change labels have been added.
- [ ] I have read and agree to the [CONTRIBUTING.md](https://github.com/cisagov/ScubaGoggles/blob/main/CONTRIBUTING.md) document.
- [ ] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [ ] All relevant repo and/or project documentation has been updated to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [ ] All new and existing tests pass.

## ✅ Pre-merge Checklist

- [ ] This PR has been smoke tested to ensure main is in a functional state when this PR is merged.
- [ ] Squash all commits into one PR level commit using the `Squash and merge` button.

## ✅ Post-merge Checklist

- [ ] Delete the branch to clean up.
- [ ] Close issues resolved by this PR if the [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) did not activate.

### CODE REVIEW

**Review by LaurenBassett — APPROVED** [review]

**Comment by jkaufman-mitre** [comment]
@buidav No users can install chat apps unless the pre-req setting is enabled.

**Comment by adhilto** [comment]
> @buidav No users can install chat apps unless the pre-req setting is enabled.

@jkaufman-mitre I agree with David on this one. I would also recommend not adding this to the baseline. My reasoning:
- Given that the policy says _not_ to do something, the addition of the prerequisite section makes it read as "Thou SHALL NOT do X. By the way, this is how you do X."
- This control is about "less secure apps that do not meet security standards for authentication." But the Prerequisite is specifically about Chat apps; that limited scope doesn't seem relevant to the scope of the policy.

**Comment by jkaufman-mitre** [comment]
@adhilto and @buidav I disagree with both of you as it does not say "Do not do X" it says "Only approved apps are allowed to be installed". However, if the pre-requisite setting is NOT ENABLED then even approved apps are not allowed to be installed which is contradictory to the policy. Therefore, without adding this to the baseline it could cause for extra confusion among users that would be avoided by adding this to the baseline.

**Comment by jkaufman-mitre** [comment]
@adhilto and @buidav Please refer to the most recent comment in issue #222 as a reference.

**Pull request closed without merging**
