### PR TITLE
Meet 1.1 changed to SHOULD

### LINKED ISSUE #203: Changes to GWS.MEET.1.1v0.1
Changes to GWS.MEET.1.1v0.1. More details will be added once the final changes have been clarified.

### PR DESCRIPTION
**Pull request by jkaufman-mitre**
## 🗣 Description ##

Changed GWS.MEET.1.1v0.1 from a SHALL to a SHOULD. In addition, made a note under the policy explaining the configuration item that is available within the meeting itself. Also, updated the last updated field for GWS.MEET.1.1v0.1.

Fixes #203 

### 💭 Motivation and context

CISA requested these changes to the Meet baseline

## ✅ Pre-approval checklist ##

- [ ] This PR has an informative and human-readable title.
- [ ] Changes are limited to a single goal - *eschew scope creep!*
- [ ] If applicable, *All* future TODOs are captured in issues, which are referenced in the PR description.
- [ ] The relevant issues PR resolves are linked preferably via [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [ ] All relevant type-of-change labels have been added.
- [ ] I have read and agree to the [CONTRIBUTING.md](https://github.com/cisagov/ScubaGoggles/blob/main/CONTRIBUTING.md) document.
- [ ] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [ ] All relevant repo and/or project documentation has been updated to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [ ] All new and existing tests pass.

## ✅ Pre-merge Checklist

- [ ] This PR has been smoke tested to ensure main is in a functional state when this PR is merged.
- [ ] Squash all commits into one PR level commit using the `Squash and merge` button.

## ✅ Post-merge Checklist

- [ ] Delete the branch to clean up.
- [ ] Close issues resolved by this PR if the [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) did not activate.

### CODE REVIEW

**Comment by tmcomeau** [comment]
@jkaufman-mitre ask @lrsmitre to either e-mail or set up a call with Google so they can confirm the relationship between the admin console-side and meeting-side controls for controlling meeting access. Why do both exist? Will the meeting-side control replace the admin console control? Which currently takes precedence? Once we get clarification we should also include a link in the "resources" to the authoritative documentation if needed. Current resources don't cover meeting-side control.

**Comment by jkaufman-mitre** [comment]
Email was sent to Google a few days ago.

**Review by LaurenBassett — CHANGES_REQUESTED** [review]
Shall needs to be changed in the baseline and tests too

**Comment by jkaufman-mitre** [comment]
Shall has already been changed to should in the baseline.

**Comment by LaurenBassett** [comment]
> Shall has already been changed to should in the baseline.

In the Rego file and tests

**Comment by adhilto** [comment]
> Email was sent to Google a few days ago.

Any update on this? Is this PR ready for review again?

**Comment by jkaufman-mitre** [comment]
I believe that this is ready for review.

**Review by adhilto — CHANGES_REQUESTED** [review]

**Comment by adhilto** [comment]
@LaurenBassett I've updated the rego

**Review by adhilto — APPROVED** [review]

**Comment by adhilto** [comment]
@LaurenBassett Please review this one as well, when you can.

**Review by LaurenBassett — APPROVED** [review]

**Pull request merged**
