### PR TITLE
Removed Policy Groups 22, 19, 18, and 12 andPolicy 15.2 from Gmail Baseline per Issue 137

### LINKED ISSUE #137: Gmail Baseline Changes
Based on an RFC comment, the following policies need to be removed from the Gmail baseline:
- Policy Group 22
- Policy Group 19
- Policy Group 18
- GMAIL.15.2v0.1
- Policy Group 12

### PR DESCRIPTION
**Pull request by jkaufman-mitre**
Based on the comments in issue #137, the following policies have been removed from the baseline:
- Policy Group 22
- Policy Group 19
- Policy Group 18
- GMAIL.15.2v0.1
- Policy Group 12

The remaining affected policies have been renumbered.

Fixes #137

### CODE REVIEW

**Comment by jkaufman-mitre** [comment]
Fixed the drift rules file. This PR Fixes #137

**Review by tmcomeau — APPROVED** [review]
Double check the table in the introduction for traceability.

**Comment by jkaufman-mitre** [comment]
Fixed Table of Contents at beginning.

**Review by LaurenBassett — CHANGES_REQUESTED** [review]
It doesn't look like the tests have been updated.

**Comment by adhilto** [comment]
Marking as blocked until #132 is complete. When that is done I can make the needed code changes here.

**Comment by adhilto** [comment]
@LaurenBassett, I've made the needed Rego changes in this branch. Could you review my code changes? Note that because of how I merged the latest from main into here, it's showing *a ton* of changes. To see just my changes, under the "Files changed" tab, you can select "Changes from all commits" and change it to just my commit, "Remove deleted controls from the rego" (cb6db95).

**Review by LaurenBassett — APPROVED** [review]

**Pull request merged**
