### PR TITLE
Removed 1.2 and 3.2 from the Calendar Baseline per Issue 133

### LINKED ISSUE #133: Remove CALENDAR.1.2 and CALENDAR.3.2
CALENDAR.1.2v0.1 and CALENDAR.3.2v0.1 needs to be removed from the baseline per an RFC comment.

### PR DESCRIPTION
**Pull request by jkaufman-mitre**
Removed the following policies from the Calendar baseline:
- CALENDAR.1.2v0.1
- CALENDAR.3.2v0.1

Fixes #133

### CODE REVIEW

**Comment by tmcomeau** [comment]
> Removed the following policies from the Calendar baseline:
> 
>     * CALENDAR.1.2v0.1
> 
>     * CALENDAR.3.2v0.1

After initial review of @adhilto comments these are being recommended for removal. Not only do we concur with the comment regarding this being confusing, but there is also overlap with 1.1 and 3.1, respectively. Lastly, there are is no separate admin control for either 1.2 or 3.2 which makes this more of a general recommendation and not a configuration item for a secure configuration baseline.

**Review by tmcomeau — CHANGES_REQUESTED** [review]
Don't forget to also remove the implementation steps for GWS.CALENDAR.1.2v0.1 and GWS.CALENDAR.3.2v0.1. It looks like this PR only removes the policies.

**Comment by jkaufman-mitre** [comment]
Removed the implementation steps for removed policies and fixed the drift rules file.

**Review by tmcomeau — APPROVED** [review]

**Comment by tmcomeau** [comment]
This one has code impact (policy removal). Does it make sense to also address the code changes via this branch/PR and then once the reviewers are happy with both the content/code changes we can tag in @mitchelbaker-cisa for final review so he doesn't have to watch the previous reviews and go-backs etc?

**Comment by adhilto** [comment]
> This one has code impact (policy removal). Does it make sense to also address the code changes via this branch/PR and then once the reviewers are happy with both the content/code changes we can tag in @mitchelbaker-cisa for final review so he doesn't have to watch the previous reviews and go-backs etc?

Yes Tommy, I like that approach. Once https://github.com/cisagov/ScubaGoggles/pull/141 is merged in I'll make the needed code changes to this branch. I'll mark this as blocked until then.

**Comment by adhilto** [comment]
@jkaufman-mitre What do you think about putting GWS.CALENDAR.1.1 and GWS.CALENDAR.3.1 into the same group? They're both related and that would prevent two singleton groups.

Something like this:
1. External Sharing Options
GWS.CALENDAR.1.1 External Sharing Options for Primary Calendars SHALL be configured to "Only free/busy information (hide event details)"
GWS.CALENDAR.1.2 External sharing options for secondary calendars SHALL be configured to "Only free/busy information (hide event details)"

**Comment by adhilto** [comment]
I just added the needed rego changes. @jkaufman-mitre did you see my earlier comment about putting 1.1 and 3.1 into the same group? I'll hold off on finishing my review until I hear back about that.

**Comment by jkaufman-mitre** [comment]
@adhilto I will merge the two together.

**Comment by jkaufman-mitre** [comment]
@adhilto Just made the changes to merge the two groups.

**Comment by jkaufman-mitre** [comment]
@adhilto Just fixed the TOC.

**Review by LaurenBassett — APPROVED** [review]

**Review by adhilto — APPROVED** [review]

**Pull request merged**
