### PR TITLE
Added Files for Automating Checking for Google Updates

### PR DESCRIPTION
**Pull request by jkaufman-mitre**
Added the files needed for the Google Update Tracking automation. the following files were added:
- update_checker.py
- update_log.csv
- updates.txt
- check-updates.yml

This script scrapes updates from the Google Product blog, performs initial triage, checks the updates.txt file to see if it has already checked this update, creates Github issue, and logs update in update_log.csv. Finally, it sends email notifications to TCO, Technical Content Development Lead, and others.

This also creates a Github action to run this checker every hour on the hour.

DO NOT MERGE YET. STILL WAITING ON A FEW THINGS NEEDED TO GET THIS TO BE FUNCTIONAL! However, all the needed code should be here.

### CODE REVIEW

**Comment by jkaufman-mitre** [comment]
I am working on fixing the pylint errors.

**Comment by jkaufman-mitre** [comment]
I have fixed some of the errors, but the since all of them are styling, I don't think they will cause issues.

**Review by LaurenBassett — APPROVED** [review]
Looks fine to me.

**Comment by jkaufman-mitre** [comment]
Some of the style changes would not be a practical use case in this context. For example using the following syntax:

with open (filename, operation):
     < other code here>

when using the file throughout the code what create a large section of indented code, when using:

file = open(filename, operation)

would be a much more practical way to open the file for this context.

**Comment by jkaufman-mitre** [comment]
Closing PR. Found another solution.

**Pull request closed without merging**
