### PR TITLE
Refactor DNS Code

### LINKED ISSUE #119: Change DoH query from hard-coded IP address to domain name
# 💡 Summary #
The DoH fallback for the SPF/DKIM/DMARC checks currently depends on a hard-coded IP address, 1.1.1.1. Refactor to use Cloudflare's domain name.

## Motivation and context ##
We want ScubaGear to be as IP-version agnostic as possible.

## Implementation notes ##
See
https://github.com/cisagov/ScubaGoggles/blob/ea2329fb5d9e2edb172ebc7c654eb61c452f6f11/scubagoggles/provider.py#L205

## Acceptance criteria ##
- [ ] Change 1.1.1.1 to cloudflare-dns.com
- [ ] Test to ensure DoH queries still work as expected

### LINKED ISSUE #120: Redefine "failure" for DNS queries
# 💡 Summary #
Our current implementation of the DNS queries needed for SPF/DKIM/DMARC, marked a query as "failed" if the traditional DNS query returns NXDOMAIN, no answers, or if some other exception occurs. In the case of failure, the query is re-tried over DoH. If that results in any exception other than NXDOMAIN, a warning is printed to the console. This issue would change it so that NXDOMAIN does not count as a failed query.

## Motivation and context ##
In practice, the current method results in lots of warnings being printed to the terminal. From conversations with the other developers, I know this confuses even them and is likely even more confusing for the users. Additionally, the fallback to DoH was added to address issues some of the pilot agencies ran into with the DNS queries failing when run inside their environment but working when ran outside of their environment. While we can’t easily test in other agency environments, at least for the one I have access to, “no answer” is the issue, not NXDOMAIN. I suspect it’s the same for the other pilot agencies that ran into issues.

As such, making this change should reduce the number of warnings printed to the terminal while hopefully still handling the error those pilots were running into.

## Implementation notes ##
See https://github.com/cisagov/ScubaGear/issues/41#issuecomment-1411086060 for more context.

## Acceptance criteria ##
- [ ] Fallback to DoH/warning not triggered on NXDOMAIN from the traditional DNS call
- [ ] Everything else DNS related works as before

### PR DESCRIPTION
**Pull request by adhilto**
## 🗣 Description ##
- Remove the hard-dependency on IPv4 for the DoH call
- Adjust the DoH logic so that DoH calls are not made when DoH is blocked
- Adjust DNS query logic so that a retry over DoH is not triggered by NXDOMAIN.
- Refactor DNS code into its own class
- Correct a few stray bugs in the DoH request

### 💭 Motivation and context
Closes #120.
Closes #119.

## 🧪 Testing
- Tested normal execution and asserted that the report was correct
- Hard-coded an exception to the regular DNS call to force DoH queries
- Tested on a VM with IPv6 connectivity (let me know if you want me to give you access)

## ✅ Pre-approval checklist ##
- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] If applicable, *All* future TODOs are captured in issues, which are referenced in the PR description.
- [x] The relevant issues PR resolves are linked preferably via [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
- [x] All relevant type-of-change labels have been added.
- [x] I have read and agree to the [CONTRIBUTING.md](https://github.com/cisagov/ScubaGoggles/blob/main/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated to reflect the changes in this PR.
- [x] Tests have been added and/or modified to cover the changes in this PR.
- [x] All new and existing tests pass.

## ✅ Pre-merge Checklist

- [x] This PR has been smoke tested to ensure main is in a functional state when this PR is merged.
- [x] Squash all commits into one PR level commit using the `Squash and merge` button.

## ✅ Post-merge Checklist

- [x] Delete the branch to clean up.
- [x] Close issues resolved by this PR if the [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) did not activate.

### CODE REVIEW

**Review by snarve — COMMENTED** [review]
Looks good!
Are there specific steps to test this issue, or just confirm there are no warnings generated in the terminal.

**Comment by adhilto** [comment]
> Looks good! Are there specific steps to test this issue, or just confirm there are no warnings generated in the terminal.

At a minimum you should make sure that the SPF, DKIM, and DMARC tests are giving correct output. The easiest way to do that might be to just run ScubaGoggles on both this branch and main, the results for those tests on both branches should match. If you wanted to be more thorough, you could repeat the tests I did (described above under "Testing") but I'm not sure how valuable that would be.

**Comment by amart241** [comment]
Code looks good for sure. Gonna run it here soon and make sure there are no errors on my side. Besides SPF, DKIM, and DMARC records is there anything else I should specifically test or look for?

**Comment by adhilto** [comment]
> Code looks good for sure. Gonna run it here soon and make sure there are no errors on my side. Besides SPF, DKIM, and DMARC records is there anything else I should specifically test or look for?

Nope, that's it.

**Review by snarve — APPROVED** [review]
Tests look good, approving MR.

**Review by amart241 — APPROVED** [review]
Code looks and run great. I approve

**Pull request merged**
